// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: communication.proto

package communication

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{1}
}
func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type Invoice struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CompanyID            string   `protobuf:"bytes,2,opt,name=companyID,proto3" json:"companyID,omitempty"`
	InvoiceName          string   `protobuf:"bytes,3,opt,name=invoiceName,proto3" json:"invoiceName,omitempty"`
	TotalPrice           float64  `protobuf:"fixed64,4,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	AmountToReceive      float64  `protobuf:"fixed64,5,opt,name=amountToReceive,proto3" json:"amountToReceive,omitempty"`
	Closed               string   `protobuf:"bytes,6,opt,name=closed,proto3" json:"closed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{2}
}
func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Invoice) GetCompanyID() string {
	if m != nil {
		return m.CompanyID
	}
	return ""
}

func (m *Invoice) GetInvoiceName() string {
	if m != nil {
		return m.InvoiceName
	}
	return ""
}

func (m *Invoice) GetTotalPrice() float64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Invoice) GetAmountToReceive() float64 {
	if m != nil {
		return m.AmountToReceive
	}
	return 0
}

func (m *Invoice) GetClosed() string {
	if m != nil {
		return m.Closed
	}
	return ""
}

type Issuer struct {
	Nif                  string   `protobuf:"bytes,1,opt,name=nif,proto3" json:"nif,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Issuer) Reset()         { *m = Issuer{} }
func (m *Issuer) String() string { return proto.CompactTextString(m) }
func (*Issuer) ProtoMessage()    {}
func (*Issuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{3}
}
func (m *Issuer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Issuer.Unmarshal(m, b)
}
func (m *Issuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Issuer.Marshal(b, m, deterministic)
}
func (m *Issuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Issuer.Merge(m, src)
}
func (m *Issuer) XXX_Size() int {
	return xxx_messageInfo_Issuer.Size(m)
}
func (m *Issuer) XXX_DiscardUnknown() {
	xxx_messageInfo_Issuer.DiscardUnknown(m)
}

var xxx_messageInfo_Issuer proto.InternalMessageInfo

func (m *Issuer) GetNif() string {
	if m != nil {
		return m.Nif
	}
	return ""
}

func (m *Issuer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Bid struct {
	Dni                  string   `protobuf:"bytes,1,opt,name=dni,proto3" json:"dni,omitempty"`
	Total                float64  `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Action               string   `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bid) Reset()         { *m = Bid{} }
func (m *Bid) String() string { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()    {}
func (*Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{4}
}
func (m *Bid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bid.Unmarshal(m, b)
}
func (m *Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bid.Marshal(b, m, deterministic)
}
func (m *Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bid.Merge(m, src)
}
func (m *Bid) XXX_Size() int {
	return xxx_messageInfo_Bid.Size(m)
}
func (m *Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Bid proto.InternalMessageInfo

func (m *Bid) GetDni() string {
	if m != nil {
		return m.Dni
	}
	return ""
}

func (m *Bid) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Bid) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Bid) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type Investor struct {
	Dni                  string   `protobuf:"bytes,1,opt,name=dni,proto3" json:"dni,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvailableMoney       float64  `protobuf:"fixed64,3,opt,name=availableMoney,proto3" json:"availableMoney,omitempty"`
	RetainedMoney        float64  `protobuf:"fixed64,4,opt,name=retainedMoney,proto3" json:"retainedMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Investor) Reset()         { *m = Investor{} }
func (m *Investor) String() string { return proto.CompactTextString(m) }
func (*Investor) ProtoMessage()    {}
func (*Investor) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{5}
}
func (m *Investor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Investor.Unmarshal(m, b)
}
func (m *Investor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Investor.Marshal(b, m, deterministic)
}
func (m *Investor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Investor.Merge(m, src)
}
func (m *Investor) XXX_Size() int {
	return xxx_messageInfo_Investor.Size(m)
}
func (m *Investor) XXX_DiscardUnknown() {
	xxx_messageInfo_Investor.DiscardUnknown(m)
}

var xxx_messageInfo_Investor proto.InternalMessageInfo

func (m *Investor) GetDni() string {
	if m != nil {
		return m.Dni
	}
	return ""
}

func (m *Investor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Investor) GetAvailableMoney() float64 {
	if m != nil {
		return m.AvailableMoney
	}
	return 0
}

func (m *Investor) GetRetainedMoney() float64 {
	if m != nil {
		return m.RetainedMoney
	}
	return 0
}

type InvoicePart struct {
	OriginalId           int32    `protobuf:"varint,1,opt,name=originalId,proto3" json:"originalId,omitempty"`
	NamePart             string   `protobuf:"bytes,2,opt,name=namePart,proto3" json:"namePart,omitempty"`
	Total                float64  `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	Amount               float64  `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Buyer                string   `protobuf:"bytes,5,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Seller               string   `protobuf:"bytes,6,opt,name=seller,proto3" json:"seller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoicePart) Reset()         { *m = InvoicePart{} }
func (m *InvoicePart) String() string { return proto.CompactTextString(m) }
func (*InvoicePart) ProtoMessage()    {}
func (*InvoicePart) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{6}
}
func (m *InvoicePart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoicePart.Unmarshal(m, b)
}
func (m *InvoicePart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoicePart.Marshal(b, m, deterministic)
}
func (m *InvoicePart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoicePart.Merge(m, src)
}
func (m *InvoicePart) XXX_Size() int {
	return xxx_messageInfo_InvoicePart.Size(m)
}
func (m *InvoicePart) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoicePart.DiscardUnknown(m)
}

var xxx_messageInfo_InvoicePart proto.InternalMessageInfo

func (m *InvoicePart) GetOriginalId() int32 {
	if m != nil {
		return m.OriginalId
	}
	return 0
}

func (m *InvoicePart) GetNamePart() string {
	if m != nil {
		return m.NamePart
	}
	return ""
}

func (m *InvoicePart) GetTotal() float64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *InvoicePart) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InvoicePart) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *InvoicePart) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "communication.Message")
	proto.RegisterType((*EmptyRequest)(nil), "communication.EmptyRequest")
	proto.RegisterType((*Invoice)(nil), "communication.Invoice")
	proto.RegisterType((*Issuer)(nil), "communication.Issuer")
	proto.RegisterType((*Bid)(nil), "communication.Bid")
	proto.RegisterType((*Investor)(nil), "communication.Investor")
	proto.RegisterType((*InvoicePart)(nil), "communication.InvoicePart")
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor_b64068f22c460ac1) }

var fileDescriptor_b64068f22c460ac1 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x6e, 0xba, 0x3f, 0xed, 0x4e, 0x69, 0x29, 0x66, 0x59, 0x42, 0x0b, 0xa8, 0x8a, 0x10, 0xea,
	0xa9, 0x42, 0xf0, 0x00, 0x88, 0x6e, 0x11, 0x44, 0xea, 0x96, 0x2a, 0xdd, 0x2b, 0x07, 0x6f, 0x3c,
	0x2d, 0x56, 0x13, 0x7b, 0x71, 0x9c, 0x48, 0xb9, 0xf0, 0x36, 0x3c, 0x05, 0xef, 0x86, 0x90, 0x1d,
	0x87, 0xcd, 0x86, 0x55, 0x24, 0x6e, 0x9e, 0xcf, 0xdf, 0x7c, 0x33, 0x9e, 0xf9, 0x12, 0x78, 0x1c,
	0xcb, 0x34, 0xcd, 0x05, 0x8f, 0xa9, 0xe6, 0x52, 0x9c, 0x2d, 0x95, 0xd4, 0x92, 0xec, 0xaf, 0x81,
	0xc1, 0x0b, 0xd8, 0x99, 0x61, 0x96, 0xd1, 0x3b, 0x24, 0x04, 0xfa, 0x0b, 0xc9, 0x4a, 0xdf, 0x3b,
	0xf1, 0x4e, 0x47, 0x91, 0x3d, 0x07, 0x07, 0xf0, 0xe0, 0x63, 0xba, 0xd4, 0x65, 0x84, 0xdf, 0x73,
	0xcc, 0x74, 0xf0, 0xcb, 0x83, 0x9d, 0x50, 0x14, 0x92, 0xc7, 0x48, 0x0e, 0x60, 0x9b, 0x33, 0xcb,
	0x1e, 0x44, 0xdb, 0x9c, 0x91, 0xe7, 0x30, 0x8a, 0x65, 0xba, 0xa4, 0xa2, 0x0c, 0x2f, 0xfc, 0x6d,
	0x2b, 0xb2, 0x02, 0xc8, 0x09, 0xec, 0xf1, 0x2a, 0xf1, 0x8a, 0xa6, 0xe8, 0xf7, 0xec, 0x7d, 0x13,
	0x22, 0x2f, 0x01, 0xb4, 0xd4, 0x34, 0xb9, 0x56, 0x3c, 0x46, 0xbf, 0x7f, 0xe2, 0x9d, 0x7a, 0x51,
	0x03, 0x21, 0xa7, 0xf0, 0x90, 0xa6, 0x32, 0x17, 0x7a, 0x2e, 0x23, 0x8c, 0x91, 0x17, 0xe8, 0x0f,
	0x2c, 0xa9, 0x0d, 0x93, 0x09, 0x0c, 0xe3, 0x44, 0x66, 0xc8, 0xfc, 0xa1, 0x2d, 0xe3, 0xa2, 0xe0,
	0x0c, 0x86, 0x61, 0x96, 0xe5, 0xa8, 0xc8, 0x21, 0xf4, 0x04, 0xbf, 0x75, 0x4f, 0x35, 0x47, 0xf3,
	0x7a, 0x61, 0x1a, 0xab, 0x1a, 0xb7, 0xe7, 0xe0, 0x2b, 0xf4, 0xce, 0x39, 0x33, 0x64, 0x26, 0x78,
	0x4d, 0x66, 0x82, 0x93, 0x31, 0x0c, 0x6c, 0x63, 0x96, 0xed, 0x45, 0x55, 0x60, 0xca, 0x56, 0x9d,
	0xd8, 0xd7, 0x79, 0x91, 0x8b, 0x2c, 0x1e, 0x9b, 0x69, 0xdb, 0x47, 0x8d, 0x22, 0x17, 0x05, 0x3f,
	0x60, 0x37, 0x14, 0x05, 0x66, 0x5a, 0xaa, 0x0d, 0x35, 0x36, 0x34, 0x44, 0x5e, 0xc3, 0x01, 0x2d,
	0x28, 0x4f, 0xe8, 0x22, 0xc1, 0x99, 0x14, 0x58, 0xba, 0x4a, 0x2d, 0x94, 0xbc, 0x82, 0x7d, 0x85,
	0x9a, 0x72, 0x81, 0xac, 0xa2, 0x55, 0xd3, 0x5c, 0x07, 0x83, 0x9f, 0x1e, 0xec, 0xb9, 0x65, 0x5e,
	0x53, 0xa5, 0xcd, 0x02, 0xa4, 0xe2, 0x77, 0x5c, 0xd0, 0x24, 0xac, 0x17, 0xdb, 0x40, 0xc8, 0x11,
	0xec, 0x9a, 0x2e, 0x0c, 0xd7, 0x75, 0xf5, 0x37, 0x5e, 0x4d, 0xa4, 0xb7, 0x79, 0x22, 0xfd, 0xb5,
	0x89, 0x8c, 0x61, 0xb0, 0xc8, 0x4b, 0x54, 0x76, 0x81, 0xa3, 0xa8, 0x0a, 0x0c, 0x3b, 0xc3, 0x24,
	0x41, 0x55, 0xaf, 0xad, 0x8a, 0xde, 0xfe, 0xee, 0xc3, 0x78, 0xda, 0x74, 0xed, 0x0d, 0xaa, 0xc2,
	0x38, 0x22, 0x84, 0xc3, 0x08, 0x29, 0x9b, 0x51, 0x75, 0x8f, 0xfa, 0x12, 0xd9, 0x1d, 0x2a, 0x72,
	0x7c, 0xb6, 0xee, 0xfa, 0xa6, 0x7d, 0x8f, 0x26, 0xad, 0x4b, 0x67, 0xfd, 0x60, 0x8b, 0x7c, 0x81,
	0x47, 0xd3, 0x6f, 0x18, 0xdf, 0x4f, 0xa5, 0x10, 0x18, 0x6b, 0x5e, 0x70, 0x5d, 0x76, 0x6b, 0x75,
	0x5d, 0x06, 0x5b, 0xe4, 0x12, 0x9e, 0x85, 0x42, 0x2b, 0xc9, 0xf2, 0x18, 0x2b, 0xd3, 0xcd, 0xe5,
	0x05, 0xd5, 0x74, 0x41, 0x33, 0x24, 0x4f, 0x5a, 0xb9, 0x15, 0xa1, 0xa3, 0xbd, 0x6b, 0x38, 0x5e,
	0xa9, 0x39, 0xcf, 0x34, 0xf4, 0x9e, 0xb6, 0xf5, 0x1c, 0xa5, 0x43, 0xf1, 0x3d, 0xec, 0xdd, 0x60,
	0x92, 0xd4, 0x1f, 0xf3, 0xe4, 0x5f, 0x05, 0x83, 0x77, 0x08, 0x7c, 0x06, 0x7f, 0xae, 0xca, 0xb9,
	0x9c, 0x49, 0xc6, 0x6f, 0xcb, 0xba, 0x62, 0xe5, 0x3f, 0xd2, 0xca, 0x3a, 0xe7, 0xac, 0x43, 0xe9,
	0x0a, 0x26, 0x56, 0x69, 0xaa, 0x90, 0x6a, 0x6c, 0x3a, 0xf2, 0x68, 0x73, 0x57, 0xe6, 0xae, 0x73,
	0x97, 0xe3, 0x4f, 0xa8, 0x3f, 0xd4, 0x9f, 0x84, 0x4b, 0xca, 0xfe, 0xcf, 0x1a, 0x2e, 0x2b, 0xd8,
	0x7a, 0xe3, 0x2d, 0x86, 0xf6, 0xd7, 0xf9, 0xee, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x6c,
	0xf9, 0xce, 0x51, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommunicationServiceClient is the client API for CommunicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicationServiceClient interface {
	ReadMarketLedger(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Message, error)
	CheckConnectivity(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	IntroduceIssuerToDatabase(ctx context.Context, in *Issuer, opts ...grpc.CallOption) (*Message, error)
	IntroduceInvestorToDatabase(ctx context.Context, in *Investor, opts ...grpc.CallOption) (*Message, error)
	SellInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*Message, error)
	TryToModifyInvestorMoney(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Message, error)
	TryToCreateInvoicePart(ctx context.Context, in *InvoicePart, opts ...grpc.CallOption) (*Message, error)
	GetAvailableInvoices(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (CommunicationService_GetAvailableInvoicesClient, error)
}

type communicationServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommunicationServiceClient(cc *grpc.ClientConn) CommunicationServiceClient {
	return &communicationServiceClient{cc}
}

func (c *communicationServiceClient) ReadMarketLedger(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/communication.CommunicationService/ReadMarketLedger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationServiceClient) CheckConnectivity(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/communication.CommunicationService/CheckConnectivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationServiceClient) IntroduceIssuerToDatabase(ctx context.Context, in *Issuer, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/communication.CommunicationService/IntroduceIssuerToDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationServiceClient) IntroduceInvestorToDatabase(ctx context.Context, in *Investor, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/communication.CommunicationService/IntroduceInvestorToDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationServiceClient) SellInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/communication.CommunicationService/SellInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationServiceClient) TryToModifyInvestorMoney(ctx context.Context, in *Bid, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/communication.CommunicationService/TryToModifyInvestorMoney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationServiceClient) TryToCreateInvoicePart(ctx context.Context, in *InvoicePart, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/communication.CommunicationService/TryToCreateInvoicePart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationServiceClient) GetAvailableInvoices(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (CommunicationService_GetAvailableInvoicesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CommunicationService_serviceDesc.Streams[0], "/communication.CommunicationService/GetAvailableInvoices", opts...)
	if err != nil {
		return nil, err
	}
	x := &communicationServiceGetAvailableInvoicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CommunicationService_GetAvailableInvoicesClient interface {
	Recv() (*Invoice, error)
	grpc.ClientStream
}

type communicationServiceGetAvailableInvoicesClient struct {
	grpc.ClientStream
}

func (x *communicationServiceGetAvailableInvoicesClient) Recv() (*Invoice, error) {
	m := new(Invoice)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommunicationServiceServer is the server API for CommunicationService service.
type CommunicationServiceServer interface {
	ReadMarketLedger(context.Context, *EmptyRequest) (*Message, error)
	CheckConnectivity(context.Context, *EmptyRequest) (*EmptyRequest, error)
	IntroduceIssuerToDatabase(context.Context, *Issuer) (*Message, error)
	IntroduceInvestorToDatabase(context.Context, *Investor) (*Message, error)
	SellInvoice(context.Context, *Invoice) (*Message, error)
	TryToModifyInvestorMoney(context.Context, *Bid) (*Message, error)
	TryToCreateInvoicePart(context.Context, *InvoicePart) (*Message, error)
	GetAvailableInvoices(*EmptyRequest, CommunicationService_GetAvailableInvoicesServer) error
}

// UnimplementedCommunicationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicationServiceServer struct {
}

func (*UnimplementedCommunicationServiceServer) ReadMarketLedger(ctx context.Context, req *EmptyRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMarketLedger not implemented")
}
func (*UnimplementedCommunicationServiceServer) CheckConnectivity(ctx context.Context, req *EmptyRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckConnectivity not implemented")
}
func (*UnimplementedCommunicationServiceServer) IntroduceIssuerToDatabase(ctx context.Context, req *Issuer) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntroduceIssuerToDatabase not implemented")
}
func (*UnimplementedCommunicationServiceServer) IntroduceInvestorToDatabase(ctx context.Context, req *Investor) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntroduceInvestorToDatabase not implemented")
}
func (*UnimplementedCommunicationServiceServer) SellInvoice(ctx context.Context, req *Invoice) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellInvoice not implemented")
}
func (*UnimplementedCommunicationServiceServer) TryToModifyInvestorMoney(ctx context.Context, req *Bid) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TryToModifyInvestorMoney not implemented")
}
func (*UnimplementedCommunicationServiceServer) TryToCreateInvoicePart(ctx context.Context, req *InvoicePart) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TryToCreateInvoicePart not implemented")
}
func (*UnimplementedCommunicationServiceServer) GetAvailableInvoices(req *EmptyRequest, srv CommunicationService_GetAvailableInvoicesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAvailableInvoices not implemented")
}

func RegisterCommunicationServiceServer(s *grpc.Server, srv CommunicationServiceServer) {
	s.RegisterService(&_CommunicationService_serviceDesc, srv)
}

func _CommunicationService_ReadMarketLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServiceServer).ReadMarketLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.CommunicationService/ReadMarketLedger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServiceServer).ReadMarketLedger(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationService_CheckConnectivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServiceServer).CheckConnectivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.CommunicationService/CheckConnectivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServiceServer).CheckConnectivity(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationService_IntroduceIssuerToDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Issuer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServiceServer).IntroduceIssuerToDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.CommunicationService/IntroduceIssuerToDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServiceServer).IntroduceIssuerToDatabase(ctx, req.(*Issuer))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationService_IntroduceInvestorToDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Investor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServiceServer).IntroduceInvestorToDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.CommunicationService/IntroduceInvestorToDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServiceServer).IntroduceInvestorToDatabase(ctx, req.(*Investor))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationService_SellInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Invoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServiceServer).SellInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.CommunicationService/SellInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServiceServer).SellInvoice(ctx, req.(*Invoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationService_TryToModifyInvestorMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Bid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServiceServer).TryToModifyInvestorMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.CommunicationService/TryToModifyInvestorMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServiceServer).TryToModifyInvestorMoney(ctx, req.(*Bid))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationService_TryToCreateInvoicePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvoicePart)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServiceServer).TryToCreateInvoicePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.CommunicationService/TryToCreateInvoicePart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServiceServer).TryToCreateInvoicePart(ctx, req.(*InvoicePart))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunicationService_GetAvailableInvoices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommunicationServiceServer).GetAvailableInvoices(m, &communicationServiceGetAvailableInvoicesServer{stream})
}

type CommunicationService_GetAvailableInvoicesServer interface {
	Send(*Invoice) error
	grpc.ServerStream
}

type communicationServiceGetAvailableInvoicesServer struct {
	grpc.ServerStream
}

func (x *communicationServiceGetAvailableInvoicesServer) Send(m *Invoice) error {
	return x.ServerStream.SendMsg(m)
}

var _CommunicationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.CommunicationService",
	HandlerType: (*CommunicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadMarketLedger",
			Handler:    _CommunicationService_ReadMarketLedger_Handler,
		},
		{
			MethodName: "CheckConnectivity",
			Handler:    _CommunicationService_CheckConnectivity_Handler,
		},
		{
			MethodName: "IntroduceIssuerToDatabase",
			Handler:    _CommunicationService_IntroduceIssuerToDatabase_Handler,
		},
		{
			MethodName: "IntroduceInvestorToDatabase",
			Handler:    _CommunicationService_IntroduceInvestorToDatabase_Handler,
		},
		{
			MethodName: "SellInvoice",
			Handler:    _CommunicationService_SellInvoice_Handler,
		},
		{
			MethodName: "TryToModifyInvestorMoney",
			Handler:    _CommunicationService_TryToModifyInvestorMoney_Handler,
		},
		{
			MethodName: "TryToCreateInvoicePart",
			Handler:    _CommunicationService_TryToCreateInvoicePart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAvailableInvoices",
			Handler:       _CommunicationService_GetAvailableInvoices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "communication.proto",
}
